index:
    path: /
    controller: App\Controller\DefaultController::index

# # login:
#     path: /login
#     controller: App\Controller\LoginController::login

# logout:
#     path: /logout

# show:
#     path : /rubrique/{id}
#     controller: App\Controller\RubriqueController::show
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
